services:

#PostgreSQL
  db:
    image: postgres:16
    container_name: vendas-db
    environment:
      POSTGRES_DB: vendas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dados_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

#Spring Boot (backend + frontend)
  app:
    build: .
    container_name: vendas-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: vendas
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  dados_postgres:
